### ISSUE TITLE
Consider moving mercury236 app

### ISSUE THREAD

**Issue by v-zhuravlev** [Shden/Shden#4]
Hi, would you consider moving mercury236 app to the new repository and then attach here as git a submodule? 

Its rather good quality application that can be used outside your Home Automation project by the others (we already actually using it with few modifications).

Thanks!

**Comment by Shden** [comment]
Hi there! Thanks for the suggestion, please have a look: https://github.com/Shden/mercury236 ))

**Comment by v-zhuravlev** [comment]
awesome, thank you!
